# Generated by Django 5.0.1 on 2024-05-06 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='education',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='userprofile.studentprofile'),
        ),
        migrations.AddField(
            model_name='experience',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='userprofile.studentprofile'),
        ),
        migrations.AddField(
            model_name='projects',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='userprofile.studentprofile'),
        ),
        migrations.AddField(
            model_name='skills',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='userprofile.studentprofile'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default='2000-01-01'),
        ),
    ]
