# Generated by Django 5.0.1 on 2024-05-07 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_remove_studentprofile_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project_image',
        ),
    ]
