# Generated by Django 5.0.1 on 2024-05-08 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_studentprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='experince_from',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='experince_portfolio',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='experince_to',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='email',
        ),
    ]
