# Generated by Django 5.0.1 on 2024-05-09 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_remove_experience_experince_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='date_of_birth',
        ),
    ]
