# Generated by Django 5.0.1 on 2024-05-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_studentdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentDetail',
        ),
    ]
