# Generated by Django 5.0.1 on 2024-05-05 23:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('organizer', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('date_and_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('career_fair', 'Career Fair'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('conference', 'Conference'), ('networking_event', 'Networking Event')], max_length=50, null=True)),
                ('target_audience', models.CharField(max_length=100, null=True)),
                ('registration_link', models.URLField(blank=True, null=True)),
                ('contact_information', models.CharField(default='', max_length=200)),
                ('images', models.ImageField(default='', upload_to='Eventsdata/images/')),
            ],
        ),
        migrations.CreateModel(
            name='StudentEventApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(choices=[('Pending', 'Pending'), ('Applied', 'Applied'), ('Expired', 'Expired')], default='Pending', max_length=10)),
                ('applied_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EventsNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_notifications_title', to='events.event')),
            ],
            options={
                'verbose_name_plural': 'Event Notifications',
            },
        ),
    ]
