# Generated by Django 5.0.1 on 2024-05-16 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
